[options]
HoldPkg     = pacman glibc
Architecture = auto

# General Options
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
ILoveCandy

# Trust
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# [multilib] is disabled by default for a lighter system, 
# can be enabled later if user needs steam/gaming.
