---
# Calamares - bootloader module
# Installs GRUB bootloader

efiBootLoader: "grub"
kernel: "/vmlinuz-linux"
img: "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"
timeout: 10

grubInstall: "true"
grubProbe: "true"
grubCfg: "true"
efiBootloaderId: "hunter-os"
