---
# Calamares - displaymanager module
# Configures the display manager after installation

displaymanagers:
    - sddm

defaultDesktopEnvironment:
    executable: "startplasma-wayland"
    desktopFile: "plasma"

basicSetup: false
