---
# Calamares - packages module
# Post-install package operations

backend: pacman

operations:
    - remove:
        - mkinitcpio-archiso
        - mkinitcpio-nfs-utils
        - nbd
        - syslinux
    - try_remove:
        - virtualbox-guest-utils
        - open-vm-tools
        - qemu-guest-agent
