---
# Calamares - users module
# User creation settings

defaultGroups:
    - name: wheel
      must_exist: true
      system: true
    - name: audio
      must_exist: false
      system: true
    - name: video
      must_exist: false
      system: true
    - name: storage
      must_exist: false
      system: true
    - name: optical
      must_exist: false
      system: true
    - name: network
      must_exist: false
      system: true

autologinGroup: autologin

doAutologin: false

sudoersGroup: wheel
sudoersConfigureWithGroup: true

setRootPassword: true
doReusePassword: true

passwordRequirements:
    minLength: 8
    maxLength: -1
    libpwquality:
        - minlen=8
        - minclass=2

allowWeakPasswords: false

userShell: /bin/bash

avatarFilePath: "~/.face"
