# Calamares Settings for HUNTER OS

modules-search: [ local ]

instances:
- id:       init_cpio
  module:   initramfscfg
  config:   initramfs.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - initcpio
  - users
  - networkcfg
  - displaymanager
  - packages
  - grubcfg
  - bootloader
  - services-systemd
  - umount
- show:
  - finished

branding: hunter
prompt-install: true
dont-chroot: false
