name: Build ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create out directory
        run: mkdir -p out

      - name: Build ISO
        run: ./build-iso.sh
      - name: Upload ISO
        uses: actions/upload-artifact@v2
        with:
          name: my-iso
          path: path/to/your/iso/file
